### ISSUE TITLE
add diet plan irrespective of user

### ISSUE THREAD

**Issue by aman98aman** [aman98aman/Dietician-Backend#1]
![WhatsApp Image 2024-07-21 at 2 20 45 PM (1)](https://github.com/user-attachments/assets/292eb8e1-3e52-4f1e-ad5d-bcb38e6155b0)
![WhatsApp Image 2024-07-21 at 2 20 45 PM](https://github.com/user-attachments/assets/7c29cfe8-dfc6-4548-a296-fdf8afeffa6b)
![WhatsApp Image 2024-07-21 at 2 20 44 PM](https://github.com/user-attachments/assets/f04453c2-a0d8-4d54-a91d-922d6e21bf08)
![WhatsApp Image 2024-07-21 at 3 36 35 PM](https://github.com/user-attachments/assets/c050c6e5-4e2a-4025-b3de-b4983ae9383b)
 I just need two help from your side ek to ye jo diet wala page ka ke bahr se diet create ho pae aur access ho pae second kuch items hai hr meal me like oats milk almounds mai data dedunga per gram ya per liter egg hai to per egg kitna proteins carbs and all hota aapko ye krna ke like maine otas ka data dal diya ke han 1 gram 50 cals hota to jaise mai diet me oats 5 gram krta hu wo 50*5 hokr aage show uska sara data bs ye aapse help chahiye

**Comment by harshit973** [comment]
ok I'll start working on it

**Comment by harshit973** [comment]
I have pushed the changes please verify

**Comment by aman98aman** [comment]
OK i will verify and let you know
